services:
  overseer.api:
    image: overseer.api
    container_name: Api
    build:
      context: .
      dockerfile: Overseer.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres

  overseer-web:
    image: overseer.web
    container_name: Web
    build:
      context: .
      dockerfile: Overseer.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3000:80"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=overseer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
  
  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: papercut
    ports:
      - 8080:80
      - 25:25